export class DeliveryActions {
  static CLEAR = 'CLEAR_DELIVERY';
  static UPDATE = 'UPDATE_DELIVERY';
  static UPDATE_TIME_AND_RANGES = 'UPDATE_DELIVERY_TIME_AND_RANGES';
  static UPDATE_ORIGIN = 'UPDATE_DELIVERY_ORIGIN';
  static UPDATE_DESTINATION = 'UPDATE_DELIVERY_DESTINATION';
  static UPDATE_DISTANCE = 'UPDATE_DELIVERY_DISTANCE';
  static UPDATE_AVAILABLE_RANGES = 'UPDATE_DELIVERY_AVAILABLE_RANGES';
  static UPDATE_FROM_CHANGE_ORDER = 'UPDATE_DELIVERY_FROM_CHANGE_ORDER';
}
